### PR TITLE
Fix pyproject toml

### PR DESCRIPTION
**Pull request by barrystokman**
### This PR adds | fixes:
- pyproject.toml was no correctly bumped to version `0.8.0` in a previous PR

- [x] Code approved by MM
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by patrikgrenfeldt — APPROVED** [review]
👍

**Review by moonso — APPROVED** [review]
👍 I usually bump with poetry, running something like `poetry version minor` but I don't think it does any more than this

**Comment by henrikstranneheim** [comment]
@barrystokman You can also take a look at how Hermes bumpes: https://github.com/Clinical-Genomics/hermes/blob/main/DEPLOYMENT.md

**Comment by henrikstranneheim** [comment]
And https://github.com/Clinical-Genomics/hermes/blob/main/.bumpversion.cfg

**Comment by barrystokman** [comment]
I did actually run `poetry version minor`, but the updated pyprject.toml was not added+commited+pushed, that was my mistake. I was hoping to fix it like this.

**Pull request merged**
